### ISSUE TITLE
Test sample file

### ISSUE THREAD

**Issue by Christoph1111** [peterhinch/micropython_remote#6]
Can you provide a sample test file? I just want to send and test it.

**Comment by peterhinch** [comment]
I don't think such a file would be any use. I have tested a number of different units and they all have different protocols. This is deliberate, to ensure that a remote control only affects the receiver of that manufacturer. If I provided a file you could transmit it, but the result would be undetectable because your receiver wouldn't recognise it.

You need to capture the signal from your transmitter so that you can replay it to the matching receiver.

**Comment by Christoph1111** [comment]
Thanks for answering, I just want to replace my arduino senders which just send some integers via ask (RH_ASK from radiohead library) to my receiver. I don't have a pico receiver. For that I need just a text sample.
Thanks in advance.

**Comment by peterhinch** [comment]
OK, I've put a file [here](http://hinch.me.uk/downstairs). It has two keys, "on" and "off" and operates a remote control in my living room.

**Comment by besi** [comment]
It would be useful to have a sample file in the repository. Also to know the structure of the data.

**Comment by peterhinch** [comment]
OK, I've now done this.
